<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-IRE7K3E" failures="1" tests="4" name="Sell the Stocks" time="74.772" errors="0" timestamp="2022-06-03T12:17:10 IST">
  <testcase classname="TestCases.DoLogin" name="doLogin" time="12.286">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	My mistake">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
My mistake
at Utilty.GenericKeyword.assertAll(GenericKeyword.java:179)
at TestCases.DoLogin.doLogin(DoLogin.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at Runner.TestNGRunner.run(TestNGRunner.java:80)
at Runner.Runner.main(Runner.java:31)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
  <testcase classname="TestCases.DoLogin" name="selectPortfolio" time="10.878"/>
  <testcase classname="TestCases.StockManagement" name="goToCompany" time="10.509"/>
  <testcase classname="TestCases.StockManagement" name="sellTheStock" time="40.431"/>
  <testcase classname="TestCases.StockManagement" name="buyTheStock" time="0.0">
    <ignored/>
  </testcase> <!-- buyTheStock -->
  <testcase classname="TestCases.StockManagement" name="quantityAfterModification" time="0.0">
    <ignored/>
  </testcase> <!-- quantityAfterModification -->
  <testcase classname="TestBase.RediffBase" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
  <testcase classname="TestCases.StockManagement" name="addStock" time="0.0">
    <ignored/>
  </testcase> <!-- addStock -->
  <testcase classname="TestBase.RediffBase" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="TestBase.RediffBase" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
</testsuite> <!-- Sell the Stocks -->
